### ISSUE TITLE
页面不能滚动

### ISSUE THREAD

**Issue by jjljyn** [F-loat/vue-simplemde#10]
你好，
我在写一个 Vue + Vue-Router 的 SPA 项目，输入框使用的你写的这个插件，很好用，我很喜欢。在使用过程中发现两个小 bug 。

1. 在使用全屏对照编辑（side-by-side）的时候，编辑完成按 ESC 退出全屏，这个流程没有问题。
问题是这样的，使用 side-by-side 后不按 ESC ，而是点击浏览器的返回按钮，再进入这个页面的时候回出现页面不能滚动的情况。再按 ESC 页面就又能滚动了。

2. 使用预览功能（preview），在文本框内可以预览 HTML 的效果，这里也没有问题。
问题是这时候再点击全屏，不按 ESC 而点击浏览器返回按钮，再进入这个页面，会出现和上面一样的问题。

目前我的解决办法是在 hideIcons 中添加了 side-by-side、fullscreen 来隐藏掉这两个功能。

**Comment by F-loat** [comment]
可以试下在activated钩子中执行以下代码，我之后看下能不能在插件中完成处理
``` javascript
const editor = this.simplemde;
if(editor.codemirror.getOption("fullScreen")) editor.toggleFullScreen();
```

**Comment by beaplat-61f** [comment]
@jjljyn 请问如何全屏对照编辑呢

**Comment by jjljyn** [comment]
@beaplat-61f 
``
export default {
  data () {
    return {
      configs: {
        toolbar: ['bold', 'italic', 'heading', '|', 'quote', 'side-by-side']
      }
    }
  }
}
``
上面`side-by-side`就是全屏对照编辑的功能，这个是功能是默认开启。

**Comment by beaplat-61f** [comment]
@jjljyn 感激不尽
