### ISSUE TITLE
bug with IOS

### ISSUE THREAD

**Issue by EveLuty** [F-loat/vue-simplemde#13]
Hello, I use this components for my project VUEJS 1.0

I import it in the main.js

it works in Safari, chome and so on, but it doesn't work in IOS (Safari, chrome). all browsers not work with the import of vue-simplemde, could you please have a look at it?

I think that it is very ease to reproducible, thank you by advance,

Best regards

**Comment by F-loat** [comment]
[SimpleMDE Markdown Editor](https://simplemde.com/)
Is the simplemde's demo work well?

**Comment by EveLuty** [comment]
Hello F-loat, I found a bug in this project, in the index.js, you open 'user strict', but after there are still the 'const', it will case the problem, so the IOS will not load this components. could you please correct this problem?

thank you

**Comment by F-loat** [comment]
Sorry, it's my mistake.
