### ISSUE TITLE
代码无法高亮，预览也没有解析

### ISSUE THREAD

**Issue by treasureDouDou** [F-loat/vue-simplemde#16]
![qq 20170614041147](https://user-images.githubusercontent.com/21187862/27102557-3daa4f04-50b8-11e7-85a0-ae7d6c59a085.png)

**Comment by doudouyoutangtang** [comment]
请问怎么回事...文档确实不太行

**Comment by F-loat** [comment]
提供下webpack的版本吧，

**Comment by lemos1235** [comment]
好像是有问题啊

**Comment by F-loat** [comment]
@lemos1235 当时写这个的时候webpack还是1.x的版本，现在可能是会有点问题，最近有其他事情在忙，过阵子会更新的，

**Comment by lemos1235** [comment]
@F-loat  刚刚在项目中尝试了一下，语法高亮是有效的。不过看了一下model绑定的是原生的字符串，而不是渲染后的html..

**Comment by lemos1235** [comment]
示例文档中有问题。但在项目中可以正常显示。总之，看起来还不错。

**Comment by superbogy** [comment]
+1

**Comment by F-loat** [comment]
需要注意下v0.4.0以后css文件都需要自行引入了，另外highlight打包出来好像有点大。。加载完成后才会生效

**Comment by F-loat** [comment]
当时simplemde的作者是根据window.hljs这个变量决定是否启用代码高亮的，所以直接在html里引用highlight.js这个文件也可以

**Comment by F-loat** [comment]
最新版还有问题的话再重开issue吧
