### ISSUE TITLE
Is it possible to only render?

### ISSUE THREAD

**Issue by janva255** [F-loat/vue-simplemde#17]
And don't show the editor?
Or how can i render a text that i made with vue simplemde, i'm using github style too

**Comment by F-loat** [comment]
You can use `this.simplemde.markdown(this.content)` get rendered html.
Or use [marked](https://github.com/chjj/marked) with markdown text.
The [github style](https://github.com/sindresorhus/github-markdown-css) is additional.

**Comment by janva255** [comment]
@F-loat Okay, thank you!

**Comment by reversesoul** [comment]
肯定给个示例代码，我这边试了，不行。this.simplemde.markdown(this.content)

**Comment by F-loat** [comment]
参考gh-pages分支

**Comment by jimmy718** [comment]
If anyone happens upon this issue and can't figure it out, `this` in @F-loat message refers to the `<vue-simple-mde>` component. 

If you have followed the documentation and added a `ref="markdownEditor"` to the component, then you can call this method in your component that uses `<vue-simple-mde>`:
```
this.$refs.markdownEditor.simplemde.markdown(value)
```
