### ISSUE TITLE
require.ensure 網址問題

### ISSUE THREAD

**Issue by xralphack** [F-loat/vue-simplemde#19]
我要使用高亮的話，請求 highlight.js 網址會變成不是絕對的

ex:
threads/15/js/highlight.ccc81c3aad1bca262474.js

請問一下可以怎麼解決呢

**Comment by F-loat** [comment]
这个应该和webpack的配置有关系，可以先试下v0.4.0这个版本还有没有问题，有的话重开issue反馈吧
