### ISSUE TITLE
error build with vue-cli [webpack]

### ISSUE THREAD

**Issue by bakatest-me** [F-loat/vue-simplemde#2]
when i build with vue-cli error this :
ERROR in static/js/vendor.48ded05f3a2124ff9079.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/vue-simplemde/index.js:10,0]

> old index.js
`const markdownEditor = require('./markdown-editor')
const VueSimplemde = {
  markdownEditor,
  install (Vue) {
    Vue.component('markdown-editor', markdownEditor)
  }
}
module.exports = VueSimplemde`

> to new 
`const markdownEditor = require('./markdown-editor')
const VueSimplemde = {
  markdownEditor:markdownEditor,
  install:function(Vue) {
    Vue.component('markdown-editor', markdownEditor)
  }
}
module.exports = VueSimplemde` 
**this work for my build**

**Comment by F-loat** [comment]
build/webpack.base.conf.js
```
{
  test: /\.js$/,
  loader: 'babel',
  include: projectRoot,
  exclude: /node_modules/
},
```
Babel will not be processed in the node_modules files and browser does not support some of the ES6 characteristics.
I will modify the index.js as you do and publish a new version.
Maybe i will compile with webpack in the future, then provide a compiled version.

**Comment by bakatest-me** [comment]
@F-loat it's so good thank you ^ ^

**Comment by F-loat** [comment]
Not at all. :)
