### ISSUE TITLE
Editor value does not show until click into?

### ISSUE THREAD

**Issue by crabvn** [F-loat/vue-simplemde#20]
When I click to the edit button. The MakrdownEditor value changed to the right value, but not show on the editor. The text only show when I click into the editor form. How can I fix that? 

Note: I had do configs set `autofocus: true` but nothing happened

Thank you,

**Comment by F-loat** [comment]
What version of vue and webpack are you using?

**Comment by crabvn** [comment]
"vue": "^2.3.3" and "webpack": "2.2.1"

**Comment by F-loat** [comment]
https://f-loat.github.io/vue-simplemde/
Does this demo have the same problem?

**Comment by crabvn** [comment]
No it does not. The issue on mine happened on a modal.

**Comment by F-loat** [comment]
Try to use `this.$refs.markdownEditor.initialize()` when the modal show.

**Comment by crabvn** [comment]
Thank :) I will do it on Monday

**Comment by crabvn** [comment]
It says initialize() is undefined.

**Comment by crabvn** [comment]
and, the editor works fine on form without modals. Is this any help?

**Comment by F-loat** [comment]
You should modify markdown-editor.vue like this:
``` javascript
mounted() {
  // this.initialize();
},
```
and after the model show do this:
``` javascript
this.$nextTick(() => {
  this.$refs.markdownEditor.initialize();
});
```

**Comment by F-loat** [comment]
I will solve the problem in the next release.

**Comment by crabvn** [comment]
Thank you. I actually have not resolved the issue yet.

**Comment by F-loat** [comment]
I think the modal is hidden or not exist at mounted hook, so markdownEditor init fail.
And reinit it after the modal show, it should work.

Actually, it should init only when the first time show.

**Comment by F-loat** [comment]
same issue, maybe help.
sparksuite/simplemde-markdown-editor#596
sparksuite/simplemde-markdown-editor#344

**Comment by blyleven** [comment]
I'm having the same problem, any updates on this?

**Comment by F-loat** [comment]
Try to refresh editor after the modal show.
``` javascript    
this.simplemde.codemirror.refresh();
```

**Comment by F-loat** [comment]
[SimpleMDE](https://github.com/NextStepWebs/simplemde-markdown-editor)'s issue

**Comment by codebykyle** [comment]
Thanks for the help @F-loat. I still have this issue, and unable to remedy it using any of the information posted here, or via upgrading to the newest version. I've tried researching the link you've provided in the last post, but it doesn't seem to link to anything. 

Is this issue resolved? How can I go about fixing it?

Thank you for the help.

**Comment by F-loat** [comment]
The link is right now. Vue-simplemde is just a small wrapper of SimpleMDE and this issue should be SimpleMDE's.

@burhanmt provided a solution in the last post of SimpleMDE#596

>$("#application-modal").focus(function () {
  simplemde.codemirror.refresh();
});
The snippet which is above is not working in Safari and Chrome.
But if I change the code like that:
    $('#modal_editarticle').on('shown.bs.modal', function () {
        simplemde.codemirror.refresh();
    });
it will work in all browsers.

**Comment by codebykyle** [comment]
Yep, thanks I see that now. My mistake. I had `.on('show.bs.modal')` which fires before, not after the modal is shown. Sorry about that. For others experiencing this:

**Make a markdown component with a ref attribute**
`<markdown-editor ref="markdown" :id="field" v-model="contentValue"></markdown-editor>`


**My Show Dialog function to show the Modal with a simplemde component**
```
        showDialog() {
            this.resetForm();
            let modal = $('#' + this.getModalId);
            let self = this;
            modal.on('shown.bs.modal', function () {
                self.$refs.markdown.simplemde.codemirror.refresh();
            });
            modal.modal('show');
        },
```

whatever is in your ref attribute on your markdown component is swapped in `self.$refs.`

Thanks for the help and _super_ quick reply, @F-loat. Appreciate it. :)
