### ISSUE TITLE
给的示例在console有错误提示

### ISSUE THREAD

**Issue by tianyuwu** [F-loat/vue-simplemde#23]
在对编辑内容进行鼠标拖动选择时，会触发一个bug，该bug导致拖动无法选择内容进行复制，console中报错如下：
Uncaught ReferenceError: selected_content is not defined
能进行一下修复吗

**Comment by F-loat** [comment]
试了一下，并没有报错，你用的是哪个版本的浏览器

**Comment by tianyuwu** [comment]
谷歌浏览器 版本：61.0.3163.100

**Comment by F-loat** [comment]
你的电脑是mac吗，我在windows系统下始终没有报这个错
你试一下 [simplemde](https://simplemde.com/) 官网的demo会不会报错，会的话就是 simplemde 的 issue 了

**Comment by tianyuwu** [comment]
是的也会报错

**Comment by F-loat** [comment]
那也有可能是 CodeMirror 的问题，你可以去反馈下，或者看有没有人也遇到这个问题，这个 issue 就先关闭了
