### ISSUE TITLE
how to disable html in editor?

### ISSUE THREAD

**Issue by paulprok** [F-loat/vue-simplemde#24]
how to deny html inside editor?
smth like `<a href="#">link</a>` should stay `<a href="#">link</a>`, not <a href="#">link</a>
thanks

**Comment by F-loat** [comment]
A way from sparksuite/simplemde-markdown-editor#243
>// get  marked instance in any way
import marked from 'marked'
// set sanitize option, to just make it ignore html input
marked.setOptions({ sanitize: true });

And now, sanitize prop has been added. (v0.4.5)

**Comment by paulprok** [comment]
wondeful!
