### ISSUE TITLE
how to disable some tags?

### ISSUE THREAD

**Issue by paulprok** [F-loat/vue-simplemde#25]
for example, I need to deny use links at all
`[title](link)` should be removed, or transform to only text like that `title`

can I do it with `configs.blockStyles.link` ?

**Comment by F-loat** [comment]
You can use `configs.previewRender` to custom the render function.

```
import marked from 'marked';

const renderer = new marked.Renderer();
renderer.link = (href, title, text) => text;

configs.previewRender = text => marked(text, { renderer })
```

tip: `configs.renderingConfig` will be ignored.

**Comment by F-loat** [comment]
Reopen this issue if you need.
