### ISSUE TITLE
在ios浏览器上的“惊喜”

### ISSUE THREAD

**Issue by boxshadow** [F-loat/vue-simplemde#28]
![qq 20171027134412](https://user-images.githubusercontent.com/8577474/32089497-f9821a3a-bb1c-11e7-8caf-64cbfc640078.jpg)

老铁看图，上面的数字是在ios 九宫格输入法的情况下输出，
全键盘无法输入中文，文字是默认获取到焦点后，待选文字输入的

**Comment by F-loat** [comment]
你试一下在[simplemde](https://simplemde.com/)和[codemirror](http://codemirror.net/)都有这个问题没

**Comment by F-loat** [comment]
估计比较可能是codemirror的bug，simplemde因为很久没更新了所以使用的codemirror的版本比较低，新版的codemirror还有这个bug的话，就没办法了

**Comment by boxshadow** [comment]
@F-loat 都有.......
