### ISSUE TITLE
自定义toolbar的时候无法设置方法

### ISSUE THREAD

**Issue by d9577** [F-loat/vue-simplemde#30]
根据文档中想要自定义工具栏按钮的图标，文档中说的是
``` javascript
toolbar: [{
            name: 'bold',
            action: SimpleMDE.toggleBold,
            className: 'fa fa-bold',
            title: '加粗'
          }}
```
但是action中的`SimpleMDE`并不存在
直接用`markdownEditor`也没有对应的`toggleBold`方法

**Comment by F-loat** [comment]
config的文档只做了简单的翻译，组件内可以使用 `this.$refs.markdownEditor.simplemde` 来获取实例化的SimpleMDE对象

**Comment by F-loat** [comment]
这个下面的表格里应该就是全部的内置工具栏图标了 [工具栏](https://github.com/F-loat/vue-simplemde/blob/master/doc/configuration_zh.md#工具栏)

**Comment by kang558** [comment]
ε=(´ο｀*)))唉，没注意到这个表格
