### ISSUE TITLE
怎么渲染html字符串 ？ 把拼接的html字符串渲染到编辑器中

### ISSUE THREAD

**Issue by kang558** [F-loat/vue-simplemde#31]
怎么渲染html字符串 ？ 因为文章是html结构的

**Comment by F-loat** [comment]
直接设置初始值就可以吧，默认是会渲染html元素的

**Comment by F-loat** [comment]
编辑状态下，html是以代码形式显示的，一般来说，编辑器也不会同时支持html和markdown的可视化编辑

**Comment by kang558** [comment]
哎，要是能像富文本编辑器那样初始化的时候渲染html到编辑器中，而不是预览的时候渲染就好了

**Comment by F-loat** [comment]
这样的话，你还是直接使用富文本编辑器比较好吧
