### ISSUE TITLE
请问输入光标是如何渲染的

### ISSUE THREAD

**Issue by Muzm** [F-loat/vue-simplemde#32]
如果可以能给我看看源码吗 最近也在写富文本编辑器这个问题一直没法解决

**Comment by Muzm** [comment]
ah~ In another branch.I Found it

**Comment by F-loat** [comment]
源码请移步[simplemde](https://github.com/sparksuite/simplemde-markdown-editor)查看，我不是这个编辑器的作者，只是针对在vue中使用做了一点封装，光标的话，应该是[codemirror](https://github.com/emmetio/codemirror)处理的
