### ISSUE TITLE
为什么我table打不出来？

### ISSUE THREAD

**Issue by lovezhao311** [F-loat/vue-simplemde#34]
| Column 1 | Column 2 | Column 3 |
| -------- | -------- | -------- |
| John     | Doe      | Male     |
| Mary     | Smith    | Female   |

这样输出的不是table..

**Comment by F-loat** [comment]
![image](https://user-images.githubusercontent.com/16759376/33480129-d76d0f9e-d6ca-11e7-9839-1adfd45a72ad.png)

没问题的啊

**Comment by F-loat** [comment]
这个应该是ok的，issue我先关闭了哈
