### ISSUE TITLE
isPreviewActive为false的情况下动态设置value不显示内容

### ISSUE THREAD

**Issue by bigStuart** [F-loat/vue-simplemde#35]
如图
[正常图片](https://pan.baidu.com/s/1sllzllb)
[不显示内容图片](https://pan.baidu.com/s/1i5akopZ)

**Comment by F-loat** [comment]
> github的输入框可以直接ctrl+v粘贴截图的

``` javascript
  const wrapper = this.simplemde.codemirror.getWrapperElement();
  const preview = wrapper.lastChild;
  preview.innerHTML = this.simplemde.options.previewRender(this.content, preview);
```

simplemde本身没有提供更新预览内容的方法，你可以在更新数据后，像上面那样手动设置下 innerHTML，点击预览时就是进行这个操作的，有这个需求的人比较多的话我再考虑在这个库里加下这个方法

**Comment by bigStuart** [comment]
晕，我居然不知道ctrl+v可以粘贴截图...搞得我还专门去网盘上传一次...[尴尬]
嗯、按照你的操作可以了
多谢啦
