### ISSUE TITLE
Image upload in Markdown system

### ISSUE THREAD

**Issue by bitfumes** [F-loat/vue-simplemde#37]
Hey bro, this editor is extremely **awesome**, but I want to know how we can upload file from our pc, like browsing file and save it and then display in our ![] content.

Please guide me.

**Comment by F-loat** [comment]
Sorry, simplemde is not support image upload currently, so you should do this yourself.
Some discussions #6 sparksuite/simplemde-markdown-editor#613.

**Comment by bitfumes** [comment]
Okay, sorry to disturb you again but can you guide me How I implement that system myself.

**Comment by F-loat** [comment]
You can customize the toolbar like add a button with a upload image method, show a modal or directly choose image and then upload it, finally change the content.
And also you can use a customized version simplemde like [daihere1993's](https://github.com/daihere1993/simplemde-markdown-editor-extend) and use the way in sparksuite/simplemde-markdown-editor#613.

**Comment by bitfumes** [comment]
Okay thanku very much for this help, I appreciate your effort

**Comment by F-loat** [comment]
Not at all. :)

**Comment by MrBhola** [comment]
install one more library along with vue-simplemde . Using  npm i simplemde-vue --save    from : https://github.com/bedus-creation/SimpleMDE

and put the following code : 
<template>
    <editor
        name="description"
        imageUploadUrl="/upload/image"
        @ImageUploadSuccess="ImageUploadSuccess"
    ></editor>
</template>
<script>
import Editor from "simplemde-vue";
export default {
    components: { Editor },
    methods: {
        ImageUploadSuccess: function(simplemde, response) {
            simplemde.codemirror.replaceSelection(
                '<img class="h-64 w-25" src ="' + response.data.link + '" >'
            );
        }
    }
};
</script>

It worked for me. Thanks.
