### ISSUE TITLE
输出的markdown，换行没有保持。

### ISSUE THREAD

**Issue by lance10030** [F-loat/vue-simplemde#38]
场景：把编辑完成的markdown文件的content保存到服务端，但是换行的信息并没有保存下来
`
 handleOutputMARKDOWN() {
        this.type = 'markdown';
        this.output = this.content;
      }
`
保存以上的content到服务端，下次请求回来继续编辑的时候还需要再次，自己手动换行。

**Comment by F-loat** [comment]
目前你服务端保存的内容中保留了换行符 `\n` 没

**Comment by lance10030** [comment]
编写的时候不会去敲换行符。我是直接将this.content 的结果保存到服务端。打出来之后是没有换行符的，就像您给出的demo page中点击‘输出MARKDOWN’得到的结果一样。是我配置错了吗？我好像没找到相关的配置项。

**Comment by F-loat** [comment]
你截图给我看一下编辑好的效果和请求回来的效果吧，然后我待会儿试一下，现在手边没电脑

**Comment by lance10030** [comment]
上传之前拿到的生成的内容就没有换行符的就像demo page中的生成结果一样
![1513666410 1](https://user-images.githubusercontent.com/23490915/34144432-80f537d0-e4cc-11e7-81b2-90b2b1daba0f.jpg)

**Comment by F-loat** [comment]
生成的内容里应该是有换行符 `\n` 的，你可以在 vue-devtools 里查看下，demo中不显示是因为 `\n` 这个字符在普通的标签里会变成空格，使用` pre` 标签就可以保留换行的效果

**Comment by lance10030** [comment]
啊，不好意思，是我疏忽了。太麻烦您了。谢谢。

**Comment by F-loat** [comment]
没事的😋，我之前也是没注意到这个

**Comment by lance10030** [comment]
我发现好像不支持。添加[TOC]自动生成目录的功能对吧？




发自网易邮箱大师


在2017年12月19日 16:13，F-loat<notifications@github.com> 写道：

没事的😋，我之前也是没注意到这个

**Comment by F-loat** [comment]
这个应该不支持，这个可以参考这个自己添加（[给marked增加TOC](http://blog.csdn.net/tujiaw/article/details/78442687)）

**Comment by lance10030** [comment]
thx
