### ISSUE TITLE
this is used in vue 1.0 or vue 2.0 ?

### ISSUE THREAD

**Issue by murilolivorato** [F-loat/vue-simplemde#4]
this is used in vue 1.0 or vue 2.0 ?

**Comment by F-loat** [comment]
Currently  only support vue2.0+

**Comment by F-loat** [comment]
support vue1.0 with  commit 6389940

**Comment by F-loat** [comment]
Support vue1.0 with  commit 6389940

**Comment by chunmu** [comment]
这么牛逼的东西  我现在才发现。

**Comment by F-loat** [comment]
嗯，主要是SimpleMDE这个库做的挺好的，我是自己准备在vue里使用，就做了一点封装

**Comment by chunmu** [comment]
我现在的应用场景是超级管理员才有编辑权限  普通成员只是展示   我好想没找到这个配置

**Comment by F-loat** [comment]
只是展示的话把markdown渲染成html不就好了，或者你想保留编辑器的样式的话，可以在初始化时手动调用下预览，并且把预览切换的按钮隐藏
