### ISSUE TITLE
我想 把select，key 等关键字高亮   该在什么地方配置

### ISSUE THREAD

**Issue by Erimons-chan** [F-loat/vue-simplemde#40]
- [ ] It's been tested on [simplemde's website](https://simplemde.com/), and there's no problem.

**Comment by F-loat** [comment]
参考文档：[marked](https://github.com/chjj/marked#highlight)
在你的代码里直接 `import marked from 'marked';`，然后配置 highlight 应该就可以了，关键字可以自己用正则匹配，也可以找个有这种功能的库

**Comment by Erimons-chan** [comment]
thanks，get
