### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by haoxl3** [F-loat/vue-simplemde#45]
I used it in my nuxt project, I got an error about 'navigator is not defined',How should I support it  vue SSR?thank you very much

**Comment by F-loat** [comment]
You can try to set `:autoinit="false"` and init it in activated hook.

``` js
this.$refs.markdownEditor.initialize()
```

**Comment by F-loat** [comment]
If not work I'll try to support it later.

**Comment by haoxl3** [comment]
sorry, I gavue up use it, I'm using ```markdown-it``` now

**Comment by F-loat** [comment]
OK, anyway, I will try to support SSR as soon as possible.
