### ISSUE TITLE
How to directly edit the content so I can add a markdown element?

### ISSUE THREAD

**Issue by kotAPI** [F-loat/vue-simplemde#48]
I'm trying to build a custom toolbar icon, when clicked injects a image link where the cursor is currently present. How can I directly append to markdown content?

I tried emitting events and  but the parent doesn't catch it. Seeking advice on how I could do something similar.

**Comment by F-loat** [comment]
``` html
<markdown-editor v-model="content"></markdown-editor>
```

Just change `content` and it will sync to simplemde.

**Comment by F-loat** [comment]
A work around about upload image: [基于vue-simplemde实现图片拖拽、粘贴功能的一些思考](https://zhuanlan.zhihu.com/p/35679561) .

**Comment by kotAPI** [comment]
Alright, thanks a lot! :)
