### ISSUE TITLE
How do i get hml only from the model for me to save in database

### ISSUE THREAD

**Issue by orimboolak** [F-loat/vue-simplemde#49]

**Comment by F-loat** [comment]
I'm not sure what youn mean but seems a simplemde's question? You can search the simplemde's repository and there are more issues for reference.

**Comment by orimboolak** [comment]
This is what i mean
How do i get the html like in the example?
![screenshot from 2018-05-25 11-03-24](https://user-images.githubusercontent.com/22850744/40533411-624c2ea0-600b-11e8-9f32-8ddaaef05225.png)

**Comment by F-loat** [comment]
like this
``` js
this.simplemde.markdown(this.content) // returns parsed html
```

**Comment by orimboolak** [comment]
this.simplemde.markdown(this.content)
Will this work If i want the raw html and not the rendered html?

**Comment by F-loat** [comment]
What means raw html.

**Comment by orimboolak** [comment]
<ul>
<li>Hello</li>
<li>Time<h1 id="hello">Hello</h1>
</li>
</ul>

**Comment by F-loat** [comment]
Use `v-text` show the raw html (better in a pre tag) and `v-html` show the rendered html.

**Comment by orimboolak** [comment]
![screenshot from 2018-05-25 11-12-24](https://user-images.githubusercontent.com/22850744/40533804-889652d8-600c-11e8-9eb4-2995f790f57d.png)

**Comment by F-loat** [comment]
The example' code: [gh-pages](https://github.com/F-loat/vue-simplemde/tree/gh-pages) .
