### ISSUE TITLE
is not working in vue 2

### ISSUE THREAD

**Issue by murilolivorato** [F-loat/vue-simplemde#5]
hello , nice code .
 I tried to install in vue 2 . but it is giving this error when I import vue-simplemde .

**Comment by F-loat** [comment]
more info provide? I tested well  just now with the gh-pages branch and the last edition.

**Comment by murilolivorato** [comment]
Hello my friend , thanks for answering .
I imported the code in NPM , like this -
```
npm install vue-simplemde --save
```
This is the code for vue 1.0 or vue 2.0 ?
after that in vue , I imported like this -
import VueSimplemde from 'vue-simplemde';

And this gave me this error -

![error4](https://cloud.githubusercontent.com/assets/19832238/23906715/958ff12c-08ad-11e7-8b9f-5f3f2b70e01f.jpg)


Thanks .

**Comment by F-loat** [comment]
Not at all. It for both vue1.0 and vue2.0 now.
Is this in your webpack configs ? If not, the same as #3 and I will fix this before long.
``` javascript
{
  resolve: {
    extensions: ['.vue'],
  }
},

**Comment by murilolivorato** [comment]
no, it didnt work

**Comment by F-loat** [comment]
extension added in 0.3.7 with commit 86e76bf34fd0c72a5d0377338e3cfd1e9cdc60a9

**Comment by murilolivorato** [comment]
Thanks for the help my friend . I did those changes .
But know it has changed the error -
![error5](https://cloud.githubusercontent.com/assets/19832238/23918835/4d783798-08d3-11e7-8284-00d78406667a.jpg)

**Comment by F-loat** [comment]
Can you provide your package.json file

**Comment by murilolivorato** [comment]
it is like this -
```
{
  "private": true,
  "scripts": {
    "webpack": "set NODE_ENV=development && webpack --hide-modules",
    "dev": "set NODE_ENV=development && webpack --hide-modules --watch",
    "production": "set NODE_ENV=production && webpack --hide-modules"
  },
  "devDependencies": {
    "axios": "^0.15.3",
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.18.0",
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-14",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "laravel-mix": "^0.5.0",
    "lodash": "^4.16.2",
    "vue": "^2.1.8",
    "vue-resource": "^1.0.3",
    "webpack": "^2.2.0-rc.3"
  },
  "dependencies": {
    "vue-simplemde": "^0.3.6",
  }
}
```

Thanks

**Comment by F-loat** [comment]
You should add the vue-loader to handle *.vue files, use [vue-cli](https://github.com/vuejs/vue-cli) maybe is the better way for you.
