### ISSUE TITLE
markdown语法输出value值没有换行符‘\n’

### ISSUE THREAD

**Issue by yatoo1993** [F-loat/vue-simplemde#50]
- [ ] It's been tested on [simplemde's website](https://simplemde.com/), and there's no problem.
怎样得到markdown输出换行\n?
**html**
`<markdown-editor v-model="mkediter" ref="markdownEditor" v-show="markdownEditor" :configs = "configs" preview-class="markdown-body " ></markdown-editor>`
  **js**
`
data: {
  mkediter: '',
  configs: {...}
}
`
得到的mkediter为字符串而换行只是空格，这再初始赋值时，修改文章时就把文章一行显示

**Comment by F-loat** [comment]
![image](https://user-images.githubusercontent.com/16759376/40832322-a8fe5fd2-65bd-11e8-977d-587d91472cec.png)
换行符是保留了的，是不是你数据储存的环节有问题

**Comment by yatoo1993** [comment]
谢谢！vue的"Mustache"（{{mkediter}}）转译的原因，用v-text/v-html是没问题的.
