### ISSUE TITLE
如何将vue-simplemde内容保存到数据库后，再次从数据库取出内容，再次编辑？

### ISSUE THREAD

**Issue by zhangwei900808** [F-loat/vue-simplemde#51]
现在我已经把vue-simplemde内容保存为html格式并保存到数据库中，但当我从数据库获取的时候展示的有html标签，这个怎么处理？
![image](https://user-images.githubusercontent.com/4385154/41594514-3bbbde26-73f6-11e8-9eb0-ca46f8960340.png)

**Comment by F-loat** [comment]
保存 markdown 格式的内容即可，而且一般有 localStorage 就够用
