### ISSUE TITLE
markdown内容过长时，需要点击编辑器才会加载后续内容

### ISSUE THREAD

**Issue by 2015Feng** [F-loat/vue-simplemde#52]
页面初始化时，绑定`v-model="content"`，在created里通过ajax取到markdown内容，设置到content上，markdown内容过长时，编辑器只显示一屏的内容，下面是空白，往下滚动，需要点击一次编辑器才能加载全部内容。

**Comment by F-loat** [comment]
请尝试原本的 simplemde 是否有这个问题，有的话我这边也没办法

**Comment by Straw-Breeze** [comment]
我也出现了这个问题，成功解决了，方法就是设置 CodeMirror 的高度 height
