### ISSUE TITLE
Use easyMDE instead of no-longer maintained simpleMDE

### ISSUE THREAD

**Issue by adamJLev** [F-loat/vue-simplemde#55]
Hi there,

First of all thanks for your work, this project has helped me a lot in getting things built fast.

There's a new "official fork" of simpleMDE called easyMDE: https://github.com/ionaru/easy-markdown-editor.
simpleMDE hasn't been updated in over 2 years now and has a lot of issues: https://github.com/sparksuite/simplemde-markdown-editor/issues

The libs are compatible, so it shouldn't be too much work.
Mainly we would just need to make this import be optional or let the user pass in an instance of "MDE" via `config`: https://github.com/F-loat/vue-simplemde/blob/master/src/markdown-editor.vue#L8

Or maybe you have a better idea, what do you think?

Thanks!

**Comment by F-loat** [comment]
``` js
resolve: {
  alias: {
    'vue$': 'vue/dist/vue.esm.js',
    'simplemde': 'easymde'
  }
},
```
`import simplemde` will get `easymde`. [[doc](https://webpack.js.org/configuration/resolve/#resolve-alias)]

**Comment by simshaun** [comment]
For anybody using the Vue cli, you can create a `vue.config.js` file in your project root with:

```js
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        simplemde: 'easymde',
      },
    },
  },
};
```

Restart Webpack and it should work.

**Comment by kolaente** [comment]
simplemde hasn't been updated since almost 4 years. IMHO switching this project to it would be a good idea...

**Comment by F-loat** [comment]
https://github.com/NikulinIlya/vue-easymde a workaround with easymde.

**Comment by kolaente** [comment]
@F-loat Yes, but as you said: It's a workaround.
