### ISSUE TITLE
my preview not work

### ISSUE THREAD

**Issue by klren0312** [F-loat/vue-simplemde#60]
![image](https://user-images.githubusercontent.com/10903843/50351125-2c5eba80-057c-11e9-8855-1c78f12cde67.png)

**Comment by F-loat** [comment]
可以多提供点信息，使用方式什么的，有复现示例更好

**Comment by klren0312** [comment]
我发现可能是被覆盖了...
![image](https://user-images.githubusercontent.com/10903843/50351403-084fa900-057d-11e9-84e9-98a3fdbae1a1.png)

**Comment by F-loat** [comment]
那你检查下引用的样式看看

**Comment by klren0312** [comment]
我发现是reset.css搞得鬼...

**Comment by F-loat** [comment]
调整下顺序应该就行吧

**Comment by klren0312** [comment]
大概看了下 我这个`h1`标签 放在了 `section`这些标签里, 触发了浏览器内置的样式 然后发现`reset.css`也没重置...  回去再看看咋搞...
