### ISSUE TITLE
Disable url detection

### ISSUE THREAD

**Issue by jaimeescano** [F-loat/vue-simplemde#63]
Hi there,
After checking documentation and other open questions, I couldn't find anything related to the "feature" of the editor related with the "detection" of URLs and converting them into links.

I'd like to add a string with a URL, but not as link. Is there an option to disable the "URL to Link" detection?

I saw the post "how to disable some tags", but this does not applies. This is more avoiding the editor converting text to links.

Regards and thanks for your hard work.
;-)
J.

**Comment by F-loat** [comment]
This is a marked issue.

``` js
import marked from 'marked';

marked.setOptions({ gfm: false });
```
