### ISSUE TITLE
Change codemirror options (to disable tabbing and use tab to switch field)

### ISSUE THREAD

**Issue by wjdp** [F-loat/vue-simplemde#64]
- [x] It's been tested on [simplemde's website](https://simplemde.com/), and there's no problem.

There's a solution for fixing tab-key behaviour here: https://github.com/sparksuite/simplemde-markdown-editor/issues/122#issuecomment-176329907

How can I use this solution with vue-simplemde. Is there a way of passing through codemirror options?

**Comment by whthT** [comment]
Under https://github.com/F-loat/vue-simplemde/pull/65 I have developed a solution for your problem. If PR is accepted, you will be able to use it as follows.

```vue
<markdown-editor :extra-keys="{'Tab': false}"></markdown-editor>
```

**Comment by whthT** [comment]
```vue
<template>
  <markdown-editor v-model="content" ref="markdownEditor"></markdown-editor>
</template>

<script>
  import markdownEditor from 'vue-simplemde/src/markdown-editor'

  export default {
    components: {
      markdownEditor
    },
    computed: {
        simplemde() {
            return this.$refs.markdownEditor.simplemde;
        }
    },
    mounted() {
        this.simplemde.codemirror.options.extraKeys['Tab'] = false;
        this.simplemde.codemirror.options.extraKeys['Shift-Tab'] = false;
    }
  }
</script>
```
