### ISSUE TITLE
不兼容IE

### ISSUE THREAD

**Issue by lin-xin** [F-loat/vue-simplemde#7]
在IE10中报多个错误

**Comment by F-loat** [comment]
具体是什么错误呢

**Comment by lin-xin** [comment]
`SCRIPT1002: 语法错误 
vendor.f58495a6f5e39457e45a.js, 行18436 字符2
SCRIPT5007: 无法获取未定义或 null 引用的属性“call” 
manifest.3073b747282e3ecc4af3.js, 行1 字符95
`

**Comment by F-loat** [comment]
嗯，是因为用到的方法ie不支持，可以引入babel-polyfill解决，我后面加webpack编译的时候把这个方法自己实现下吧

**Comment by lin-xin** [comment]
我有引进这个，解决了其他不兼容IE的问题 ，但是还存在这问题。你有时间也可以尝试一下。

**Comment by F-loat** [comment]
好的，可能是对node_modules中的文件无效，我尽快解决下

**Comment by F-loat** [comment]
嗯，我的demo里没有引入babel-polyfill，引入后ie11是没有问题的，ie10由于不支持const这个关键字，会报语法错误，下个版本将提供编译后的文件，就没有这些问题了

**Comment by F-loat** [comment]
`import markdownEditor from 'vue-simplemde/src/markdown-editor'` 使用这种方式引入，就可以被babel处理了

**Comment by LifengTang** [comment]
你好，  IE10的问题您是怎么解决的

**Comment by F-loat** [comment]
@LifengTang 用 webpack 打包时做了 es6 代码的转换

**Comment by LifengTang** [comment]
@F-loat  你的项目可以运行，  我的一个项目 在 IE10报语法错误，  es6 没有转化成  es5,

我也用 了 babel

**Comment by F-loat** [comment]
版本和用法贴一下

**Comment by LifengTang** [comment]
webpack config:  
module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        css: 'vue-style-loader!css-loader',
                        less: 'vue-style-loader!css-loader!less-loader'
                    },
                    postLoaders: {
                        html: 'babel-loader'
                    }
                }
            },
            {
                test: /iview\/.*?js$/,
                loader: 'happypack/loader?id=happybabel',
                exclude: /node_modules/
            },
            {
                test: /\.js$/,
                loader: 'happypack/loader?id=happybabel',
                exclude: /node_modules/
            },
            {
                test: /\.js[x]?$/,
                include: [resolve('src')],
                exclude: /node_modules/,
                loader: 'happypack/loader?id=happybabel'
            },
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader?minimize', 'autoprefixer-loader'],
                    fallback: 'style-loader'
                })
            },
            {
                test: /\.less$/,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader?minimize', 'autoprefixer-loader', 'less-loader'],
                    fallback: 'style-loader'
                }),
            },
            {
                test: /\.(gif|jpg|png|woff|svg|eot|ttf)\??.*$/,
                loader: 'url-loader?limit=1024'
            },
            {
                test: /\.(html|tpl)$/,
                loader: 'html-loader'
            }
        ]
    },
    plugins: [
        new HappyPack({
            id: 'happybabel',
            loaders: ['babel-loader'],
            threadPool: happyThreadPool,
            verbose: true
        })
    ],
    resolve: {
        extensions: ['.js', '.vue'],
        alias: {
            'vue': 'vue/dist/vue.esm.js',
            '@': resolve('../src'),
        }
    }

package config:

 "dependencies": {
    "area-data": "^1.0.0",
    "axios": "^0.17.1",
    "babel-polyfill": "^6.26.0",
    "clipboard": "^1.7.1",
    "countup": "^1.8.2",
    "cropperjs": "^1.2.2",
    "cross-env": "^5.1.4",
    "echarts": "^3.8.5",
    "html2canvas": "^0.5.0-beta4",
    "iview": "^2.13.0",
    "iview-area": "^1.5.16",
    "js-cookie": "^2.2.0",
    "rasterizehtml": "^1.2.4",
    "simplemde": "^1.11.2",
    "sortablejs": "^1.7.0",
    "tinymce": "^4.7.4",
    "vue": "^2.5.13",
    "vue-router": "^3.0.1",
    "vue-virtual-scroller": "^0.10.6",
    "vuex": "^3.0.1",
    "xlsx": "^0.11.17"
  },
  "devDependencies": {
    "autoprefixer-loader": "^3.2.0",
    "babel": "^6.23.0",
    "babel-core": "^6.23.1",
    "babel-eslint": "^8.2.1",
    "babel-loader": "^7.1.2",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.12.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-stage-3": "^6.24.1",
    "babel-runtime": "^6.11.6",
    "clean-webpack-plugin": "^0.1.17",
    "copy-webpack-plugin": "^4.3.1",
    "css-hot-loader": "^1.3.5",
    "css-loader": "^0.28.8",
    "ejs-loader": "^0.3.0",
    "eslint": "^4.15.0",
    "eslint-config-google": "^0.9.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-html": "^4.0.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.6",
    "happypack": "^4.0.0",
    "html-loader": "^0.5.4",
    "html-webpack-plugin": "^2.28.0",
    "less": "^2.7.3",
    "less-loader": "^4.0.5",
    "semver": "^5.4.1",
    "style-loader": "^0.19.1",
    "unsupported": "^1.1.0",
    "url-loader": "^0.6.2",
    "vue-hot-reload-api": "^2.2.4",
    "vue-html-loader": "^1.2.3",
    "vue-i18n": "^5.0.3",
    "vue-loader": "^13.7.0",
    "vue-style-loader": "^3.0.3",
    "vue-template-compiler": "^2.5.13",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.10.1",
    "webpack-merge": "^4.1.1",
    "webpack-uglify-parallel": "^0.1.4"
  }

**Comment by LifengTang** [comment]
@F-loat  我们是参考 iview admin 这个项目的

**Comment by F-loat** [comment]
你好像并没有用这个库？应该不会有兼容问题啊，引用 babel-polyfill 了没

**Comment by LifengTang** [comment]
plugins: [
        new HappyPack({
            id: 'happybabel',
            loaders: ['babel-loader'],
            threadPool: happyThreadPool,
            verbose: true
        })
    ]

用了的，  babel-polyfill 也用了，  这个可以解决 在 IE11的问题

**Comment by F-loat** [comment]
没看到有这个依靠，那你把使用部分的代码贴下

**Comment by LifengTang** [comment]
非常感谢， 用了你的项目的配置， 可以工作了
