### ISSUE TITLE
如何渲染数学公式呢？

### ISSUE THREAD

**Issue by Straw-Breeze** [F-loat/vue-simplemde#73]
例如 katex，或者是 MathJax

**Comment by Straw-Breeze** [comment]
特指的 preview 预览区

**Comment by F-loat** [comment]
你可以先参考这个研究下，有空我再看看

https://ahuigo.github.io/a/md.html

https://github.com/ahuigo/a/blob/master/md.html

**Comment by Straw-Breeze** [comment]
感谢，我最终使用 katex 插件配合 autorender 方法解决了这个问题

**Comment by F-loat** [comment]
很赞！具体实现在 pr 里接着讨论 #74
