### ISSUE TITLE
Error on Nuxt

### ISSUE THREAD

**Issue by pdthang** [F-loat/vue-simplemde#75]
I tried to use vue-simplemde on Nuxt based on tutorial  
https://github.com/F-loat/vue-simplemde/tree/master/examples/nuxt 

However i got error 
```
[Vue warn]: Unknown custom element: <vue-simplemde> - did you register the component correctly?
```

My nuxt version is 2.11.0
Do you have any solution?

Thank you

**Comment by F-loat** [comment]
``` js
// nuxt-simplemde-plugin.js
import Vue from 'vue'
import VueSimplemde from 'vue-simplemde'
import 'simplemde/dist/simplemde.min.css'

Vue.component('vue-simplemde', VueSimplemde)
```

**Comment by pdthang** [comment]
> ```js
> // nuxt-simplemde-plugin.js
> import Vue from 'vue'
> import VueSimplemde from 'vue-simplemde'
> import 'simplemde/dist/simplemde.min.css'
> 
> Vue.component('vue-simplemde', VueSimplemde)
> ```

Your solution works well.
