### ISSUE TITLE
TypeError: Cannot read property 'simplemde' of undefined

### ISSUE THREAD

**Issue by pdthang** [F-loat/vue-simplemde#76]
I use vue-simplemde on Nuxt based on tutorial
```
<client-only placeholder="Loading ...">
     <vue-simplemde ref="markdownEditor" :configs="configs" />
</client-only>
```
```js
data() {
    return {
      configs: {
        autofocus: true,
        promptURLs: true,
        toolbar: [
          {
            name: 'bold',
            action: this.$refs.markdownEditor.simplemde.toggleBold,
            className: 'fa fa-bold',
            title: 'Bold'
          }
        ]
       }
    }
}
```
However i got error
```
Error in data(): "TypeError: Cannot read property 'simplemde' of undefined" 
```

My nuxt version is 2.11.0
Do you have any solution?

Thank you

**Comment by F-loat** [comment]
``` js
data() {
  return {
    action: this.toggleBold
  }
},
methods: {
  toggleBold() {
    this.$refs.markdownEditor.simplemde.toggleBold()
  }
}
```

You should avoid accessing $refs from within templates or computed properties.

https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements

**Comment by pdthang** [comment]
> ```js
> data() {
>   return {
>     action: this.toggleBold
>   }
> },
> methods: {
>   toggleBold() {
>     this.$refs.markdownEditor.simplemde.toggleBold()
>   }
> }
> ```
> 
> You should avoid accessing $refs from within templates or computed properties.
> 
> https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements

Thank you so much. It works now
