### ISSUE TITLE
请问是否删除了 vue-simplemde/src/markdown-editor ？

### ISSUE THREAD

**Issue by peteryuanpan** [F-loat/vue-simplemde#81]
您好，我这边安装项目时遇到了一个这个报错

 ERROR  Failed to compile with 1 errors                                                                                          下午9:03:16

This dependency was not found:

* vue-simplemde/src/markdown-editor in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/widgets/markdown/markdown.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vue-simplemde/src/markdown-editor

接下来，我按照提示运行「npm install --save vue-simplemde/src/markdown-editor」，结果如下

npm install --save vue-simplemde/src/markdown-editor
npm ERR! code ENOLOCAL
npm ERR! Could not install from "vue-simplemde/src/markdown-editor" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peteryuanpan/.npm/_logs/2020-04-20T12_34_23_352Z-debug.log

但是我同事反馈之前运行这个命令是没有问题的，请问是否删除了 vue-simplemde/src/markdown-editor ？因为目前 https://github.com/F-loat/vue-simplemde/tree/master/src 中是没有markdown-editor 的

另外，我继续执行 npm install --save vue-simplemde 是可以的，也把https://github.com/qbox/mars/tree/develop/website 中能执行的 npm install 都执行了，测试依然会报错

如果您知晓 vue-simplemde/src/markdown-editor 的一些信息，请告诉我，目前该如何安装，感谢

**Comment by F-loat** [comment]
可以参考 readme 修改下使用方式，文件结构做过调整，最好避免直接引用具体文件

**Comment by peteryuanpan** [comment]
您好，我这边将 ./src/widgets/markdown/markdown.vue 中

import markdownEditor from 'vue-simplemde/src/markdown-editor'
改为
import markdownEditor from 'vue-simplemde'

就好了
