### ISSUE TITLE
Vetur & typescript: Cannot find module 'vue-simplemde'. Vetur(2307)

### ISSUE THREAD

**Issue by zolomatok** [F-loat/vue-simplemde#84]
- [x] It's been tested on [simplemde's website](https://simplemde.com/), and there's no problem.

`import MDE from 'vue-simplemde'`

I get the following error from Vetur when I import **vue-simplemde** in a typescript Vue project:
`Cannot find module 'vue-simplemde'. Vetur(2307)`
It's only a Vetur error, the code compiles fine.

Other npm packages like `axios` and `showdown` don't generate this error.
`"vue-simplemde": "^1.0.6"` is in package.json

**Comment by chengbing20** [comment]
tsconfig.json file
`"paths": {
      "@/*": [ "src/*" ]
    }`
modify
`"paths": {
      "@": [ "src/*" ]
    }`
