### ISSUE TITLE
Changing the config setup in initialise to the spread operator broke in IE

### ISSUE THREAD

**Issue by kirkbushell** [F-loat/vue-simplemde#88]
One of my users reported that there was a problem rendering one of our pages in vue js - in chrome and firefox, there were no issues. However they were running IE. I tested also on IE on Windows 10 and saw the same problem.

I was able to isolate the issue to a change a couple of months ago in the configuration setup in initialise, which was updated to use the spread operator, apparently without checking browser support.

That change needs to be reverted, as the plugin is currently broken in IE and wil completely crash vue rendering whenever simplemde is used.

**Comment by F-loat** [comment]
try to use the build files

``` js
 import VueSimplemde from 'vue-simplemde/dist/VueSimpleMDE.common.js'
```

**Comment by kirkbushell** [comment]
Shouldn't this do exactly that?

> import VueSimplemde from 'vue-simplemde'

If not, perhaps that should be updated?

**Comment by F-loat** [comment]
I think it depends on your build config and use the vue file is better with vue-cli@latest.

**Comment by kirkbushell** [comment]
Fair enough, thanks for quick response!
