### ISSUE TITLE
v-model is broken

### ISSUE THREAD

**Issue by JoshuaLowe1002** [F-loat/vue-simplemde#91]
Hey @F-loat 

Great work on this!

I'm having issues with v-model. The code here (https://gist.github.com/JoshuaLowe1002/295554ef3b285635807c1809eab31b7c) should on the title click get the content of the markdown editor however it does not. Am I doing something wrong?

Any advice is appreciated!

**Comment by grantholle** [comment]
I'm also having issues. It isn't reactive in that, if I change the value outside of the editor, the content doesn't update to reflect that new value.

**Comment by l5769389** [comment]
don't use  v-model   use:
:value="content"

**Comment by grantholle** [comment]
@l5769389 how would you get the updated value? Using `@input`?

**Comment by F-loat** [comment]
Hi all, sorry to take so long to response. There is a [break change](https://v3.vuejs.org/guide/migration/v-model.html#v-model) with v-model in vue@3 which should be fixed now.

Please update your deps and and report any issues, thanks.

``` sh
npm i vue-simplemde@latest
```
